before_script:
  - export DOCKER_REGISTRY=$(([[ -n $DOCKER_REGISTRY ]] && echo $DOCKER_REGISTRY) || echo "docker.joell.dev")
  - export NAME=$(([[ -n $NAME ]] && echo $NAME || echo $CI_PROJECT_NAME) | tr '[:upper:]' '[:lower:]')
  - export NAMESPACE=$(([[ -n $NAMESPACE ]] && echo $NAMESPACE || echo $CI_PROJECT_NAMESPACE) | tr '[:upper:]' '[:lower:]')

  - export CONTAINER_NAME=$DOCKER_REGISTRY/$NAMESPACE/$NAME

  - export VERSION="$(git describe --long 2>/dev/null || echo $(git describe --abbrev=0 2>/dev/null || echo 0.0.0)-g$CI_COMMIT_SHORT_SHA)"
  - export IMAGE="$CONTAINER_NAME:$VERSION"

stages:
  - build
  - deploy

build:
  image: openjdk:11
  stage: build
  tags: [ docker ]
  script:
    - ./gradlew jib --image $IMAGE -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_PASS
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - kubectl version
    - kubectl config get-contexts
    - cd infra/kubernetes/app
    - kustomize edit set image $IMAGE
    - kustomize build | kubectl apply -n bombastic -f -
    - kubectl rollout status deployment/api -n bombastic --timeout=10m
  only:
    - main