apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: apple-certificate
    namespace: bombastic
    type: Opaque
    files:
      - "certs/apple.p8"
  - name: jwks-certificates
    namespace: bombastic
    type: Opaque
    files:
      - "certs/jwks/369241K3WP.pem"

generatorOptions:
  disableNameSuffixHash: true