spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres

apple:
  keyId: REPLACE_ME
  teamId: REPLACE_ME
  clientId: dev.bombastic.app

r2dbc.migrate.resources-paths:
  - classpath:/db/migration/*.sql