spring:
  r2dbc:
    url: r2dbc:postgresql://db-postgres.joell.dev/bombastic
    username: bombastic

apple:
  keyId: REPLACE_ME
  teamId: REPLACE_ME
  certificatePath: REPLACE_ME
  clientId: dev.bombastic.app


springfox:
  documentation:
    swagger-ui:
      base-url: "/api"

r2dbc.migrate.resources-paths:
  - classpath:/db/migration/*.sql