spring:
  r2dbc:
    url: r2dbc:postgresql://db-postgres.joell.dev/bombastic
    username: bombastic
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

apple:
  keyId: REPLACE_ME
  teamId: REPLACE_ME
  certificatePath: REPLACE_ME
  clientId: dev.bombastic.app

springfox:
  documentation:
    swagger-ui:
      base-url: "/api"

r2dbc.migrate.resources-paths:
  - classpath:/db/migration/*.sql