spring:
  r2dbc:
    url: r2dbc:postgresql://db-postgres.joell.dev/bombastic
    username: bombastic
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

btc:
  ppid: test
  wallet.watchKey:
    data: vpub5UJL5nZ5JKp4qM2RsZXwQ4EpTzXPPzPcbKuKFw6yodP3cvSFa5WG57VmygCSGuFGVsB948p3b3EQuEUKFw8PEGaJnWYhSeaqUM3ApLJkHou

apple:
  keyId: REPLACE_ME
  teamId: REPLACE_ME
  certificatePath: REPLACE_ME
  clientId: dev.bombastic.app

springfox:
  documentation:
    swagger-ui:
      base-url: "/api"

r2dbc.migrate.resources-paths:
  - classpath:/db/migration/*.sql