apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api-app
          image: api-image
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 2
            successThreshold: 2
            httpGet:
              port: 8080
              path: /actuator/health
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: apple.certificatePath
              value: /app/certs/apple.p8
            - name: jwks.certificateDirectory
              value: /app/certs/jwks
            - name: spring.r2dbc.password
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password
            - name: apple.keyId
              valueFrom:
                secretKeyRef:
                  name: apple-config
                  key: keyId
            - name: apple.teamId
              valueFrom:
                secretKeyRef:
                  name: apple-config
                  key: teamId

          volumeMounts:
            - mountPath: /app/certs
              name: apple-certificate
            - mountPath: /app/certs/jwks
              name: jwk-certificates
      volumes:
        - name: apple-certificate
          secret:
            secretName: apple-certificate
        - name: jwk-certificates
          secret:
            secretName: jwks-certificates